version: "3"

services: 

  mysql:

    image: mysql:5.6
    container_name: database
    restart: always
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - wpnet
    environment:
      - MYSQL_ROOT_PASSWORD=redhat
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wpuser
      - MYSQL_PASSWORD=redhat@123#


  wordpress:

    image: wordpress:latest
    container_name: wordpress
    restart: always
    volumes:
      - wordpress-data:/var/www/html/
    networks:
      - wpnet
    ports:
      - "80:80"
    environment:
      - WORDPRESS_DB_HOST=database
      - WORDPRESS_DB_USER=wpuser
      - WORDPRESS_DB_PASSWORD=redhat@123#
      - WORDPRESS_DB_NAME=wordpress


networks:
  wpnet:

volumes:
  wordpress-data:
  mysql-data:

